# Generated by Django 6.0.4 on 2026-04-26 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название товара')),
                ('price', models.PositiveIntegerField(help_text='Цена указывается в минорных единицах валюты. Например, 1000 = 10.00 $', verbose_name='Цена (в центах)')),
                ('description', models.TextField(blank=True, default='')),
            ],
        ),
    ]
